version: "3.8"

services:
  openwebrx-usrp-auto:
    image: jketterl/openwebrx:latest
    container_name: openwebrx-usrp-auto
    restart: unless-stopped
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    ports:
      - "8073:8073"
    volumes:
      - ./openwebrx-usrp-auto-config:/etc/openwebrx
      - /usr/share/uhd/images:/usr/share/uhd/images:ro
    environment:
      - UHD_IMAGES_DIR=/usr/share/uhd/images
      - UHD_LOG_LEVEL=info
      - OPENWEBRX_ADMIN_USER=admin
      - OPENWEBRX_ADMIN_PASSWORD=admin
    tmpfs:
      - /tmp/openwebrx:rw,noexec,nosuid,size=100m
    networks:
      - openwebrx

networks:
  openwebrx:
    driver: bridge