<!-- @constitutional-exemption Article-IV-4.3 issue:#11 — Component state handling (loading/error/empty UI) deferred to UX improvement phase -->
<script lang="ts">
	import { getContext } from 'svelte';

	import type { KismetDevice } from '$lib/kismet/types';
	import {
		activeBands,
		isolatedDeviceMAC,
		isolateDevice,
		toggleBand as toggleGlobalBand
	} from '$lib/stores/dashboard/dashboard-store';
	import {
		busyAPs,
		fetchReconData,
		gpsTracked,
		hiddenNetworks,
		reconAlerts,
		reconStatus,
		reconTargets,
		weakSecurityTargets,
		wpsTargets
	} from '$lib/stores/dashboard/recon-store';
	import { kismetStore, setWhitelistMAC } from '$lib/stores/tactical-map/kismet-store';

	import { filterAndSortDevices, type SortColumn } from './devices/device-filters';
	import DeviceSubTabs from './devices/DeviceSubTabs.svelte';
	import DeviceTable from './devices/DeviceTable.svelte';
	import DeviceToolbar from './devices/DeviceToolbar.svelte';
	import DeviceWhitelist from './devices/DeviceWhitelist.svelte';
	import IntelCategoryView from './devices/IntelCategoryView.svelte';

	const dashboardMap = getContext<
		{ flyTo: (lat: number, lon: number, zoom?: number) => void } | undefined
	>('dashboardMap');

	let searchQuery = $state('');
	let whitelistedMACs: string[] = $state([]);
	let sortColumn: SortColumn = $state('rssi');
	let sortDirection: 'asc' | 'desc' = $state('desc');
	let selectedMAC: string | null = $state(null);
	let expandedMAC: string | null = $state(null);
	let shouldHideNoSignal = $state(true);
	let shouldShowOnlyWithClients = $state(false);
	let activeSubTab = $state('all');

	/* ── Intel tab definitions ──────────────────────── */

	const INTEL_TABS = [
		{ id: 'all', label: 'ALL' },
		{ id: 'weak-security', label: 'WEAK SEC' },
		{ id: 'wps', label: 'WPS' },
		{ id: 'hidden', label: 'HIDDEN' },
		{ id: 'busy-aps', label: 'BUSY APs' },
		{ id: 'gps', label: 'GPS' },
		{ id: 'alerts', label: 'ALERTS' },
		{ id: 'whitelist', label: 'WHITELIST' }
	];

	const INTEL_DESCRIPTIONS: Record<string, string> = {
		'weak-security':
			'Networks using Open, WEP, or TKIP encryption — vulnerable to interception or cracking. These are high-priority targets for security assessment.',
		wps: 'Access points with Wi-Fi Protected Setup enabled. WPS PINs can be brute-forced, bypassing WPA/WPA2 encryption entirely.',
		hidden: 'Cloaked networks or devices broadcasting without an SSID. Hidden networks are still detectable and often indicate sensitive infrastructure.',
		'busy-aps':
			'Access points with connected clients. High client counts indicate important infrastructure or potential targets for deauthentication.',
		gps: 'Devices with GPS location data captured. Useful for physical tracking, wardriving maps, and correlating device positions.',
		alerts: 'Security alerts generated by Kismet during monitoring — rogue APs, deauthentication attacks, SSID spoofing, and other anomalies.'
	};

	/* ── Sort / row click handlers ──────────────────── */

	function handleSort(col: SortColumn) {
		if (sortColumn === col) {
			sortDirection = sortDirection === 'asc' ? 'desc' : 'asc';
			return;
		}
		sortColumn = col;
		sortDirection = col === 'mac' ? 'asc' : 'desc';
	}

	function handleApClick(device: KismetDevice) {
		if ($isolatedDeviceMAC === device.mac) {
			isolateDevice(null);
			selectedMAC = null;
			expandedMAC = null;
		} else {
			isolateDevice(device.mac);
			selectedMAC = device.mac;
			expandedMAC = device.mac;
		}
	}

	function handleClientClick(device: KismetDevice) {
		if ($isolatedDeviceMAC === device.parentAP) {
			isolateDevice(null);
			selectedMAC = null;
			expandedMAC = null;
		} else {
			isolateDevice(device.parentAP ?? '');
			selectedMAC = device.mac;
		}
	}

	function handleStandaloneClick(device: KismetDevice) {
		if (selectedMAC === device.mac) {
			selectedMAC = null;
			expandedMAC = null;
		} else {
			selectedMAC = device.mac;
			expandedMAC = expandedMAC === device.mac ? null : device.mac;
		}
	}

	function flyToDevice(device: KismetDevice) {
		const loc = device.location;
		if (loc?.lat && loc.lon && dashboardMap) dashboardMap.flyTo(loc.lat, loc.lon, 17);
	}

	function handleRowClick(device: KismetDevice) {
		if (device.clients?.length) handleApClick(device);
		else if (device.parentAP) handleClientClick(device);
		else handleStandaloneClick(device);
		flyToDevice(device);
	}

	function clearIsolation() {
		isolateDevice(null);
		selectedMAC = null;
		expandedMAC = null;
	}

	function triggerRecon() {
		fetchReconData({ type: 'all', sort: 'signal', showClients: true, alerts: true });
	}

	/* ── Device filtering for ALL tab ───────────────── */

	const RENDER_CAP = 200;

	let allDevices = $derived(
		filterAndSortDevices($kismetStore.devices, $isolatedDeviceMAC, {
			searchQuery,
			shouldHideNoSignal,
			shouldShowOnlyWithClients,
			activeBands: $activeBands,
			sortColumn,
			sortDirection
		})
	);

	let renderedDevices = $derived(allDevices.slice(0, RENDER_CAP));

	/* ── Tab counts (derived from recon data) ───────── */

	let subTabCounts = $derived({
		all: allDevices.length,
		'weak-security': $weakSecurityTargets.length,
		wps: $wpsTargets.length,
		hidden: $hiddenNetworks.length,
		'busy-aps': $busyAPs.length,
		gps: $gpsTracked.length,
		alerts: $reconAlerts.length,
		whitelist: 0
	});

	/* ── Extra columns per Intel category ───────────── */

	const wpsExtraColumns = [
		{
			id: 'wps_version',
			label: 'WPS VER',
			render: (t: import('$lib/stores/dashboard/recon-store').ReconTarget) =>
				t.wps_version ? `v${t.wps_version}` : '?'
		}
	];

	const busyExtraColumns = [
		{
			id: 'client_list',
			label: 'CLIENT MACs',
			render: (t: import('$lib/stores/dashboard/recon-store').ReconTarget) =>
				t.associated_clients?.slice(0, 3).join(', ') || '-'
		}
	];

	const gpsExtraColumns = [
		{
			id: 'gps_lat',
			label: 'LAT',
			render: (t: import('$lib/stores/dashboard/recon-store').ReconTarget) =>
				t.latitude ? t.latitude.toFixed(5) : '-'
		},
		{
			id: 'gps_lon',
			label: 'LON',
			render: (t: import('$lib/stores/dashboard/recon-store').ReconTarget) =>
				t.longitude ? t.longitude.toFixed(5) : '-'
		}
	];

	/* ── Lifecycle ──────────────────────────────────── */

	$effect(() => {
		if ($isolatedDeviceMAC && !$kismetStore.devices.has($isolatedDeviceMAC)) {
			isolateDevice(null);
		}
	});

	$effect(() => {
		if ($reconStatus === 'idle') triggerRecon();
	});

	let apsWithClientsCount = $derived.by(() => {
		let count = 0;
		$kismetStore.devices.forEach((d) => {
			if (d.clients && d.clients.length > 0) count++;
		});
		return count;
	});
</script>

<div class="devices-panel">
	<DeviceToolbar
		deviceCount={allDevices.length}
		renderedCount={renderedDevices.length}
		isolatedMAC={$isolatedDeviceMAC}
		{searchQuery}
		activeBands={$activeBands}
		{shouldHideNoSignal}
		{shouldShowOnlyWithClients}
		{apsWithClientsCount}
		onClearIsolation={clearIsolation}
		onSearchChange={(q) => (searchQuery = q)}
		onToggleBand={toggleGlobalBand}
		onToggleNoSignal={() => (shouldHideNoSignal = !shouldHideNoSignal)}
		onToggleOnlyWithClients={() => (shouldShowOnlyWithClients = !shouldShowOnlyWithClients)}
	/>

	<DeviceSubTabs
		activeTab={activeSubTab}
		counts={subTabCounts}
		tabs={INTEL_TABS}
		onTabChange={(tab) => (activeSubTab = tab)}
	/>

	{#if activeSubTab === 'whitelist'}
		<div class="whitelist-view">
			<DeviceWhitelist
				{whitelistedMACs}
				onAdd={(mac) => {
					whitelistedMACs = [...whitelistedMACs, mac];
					setWhitelistMAC(mac);
				}}
				onRemove={(mac) => {
					whitelistedMACs = whitelistedMACs.filter((m) => m !== mac);
				}}
			/>
		</div>
	{:else if activeSubTab === 'weak-security'}
		<IntelCategoryView
			title="Weak Security"
			description={INTEL_DESCRIPTIONS['weak-security']}
			targets={$weakSecurityTargets}
			reconStatus={$reconStatus}
			onRefresh={triggerRecon}
		/>
	{:else if activeSubTab === 'wps'}
		<IntelCategoryView
			title="WPS Targets"
			description={INTEL_DESCRIPTIONS.wps}
			targets={$wpsTargets}
			reconStatus={$reconStatus}
			onRefresh={triggerRecon}
			extraColumns={wpsExtraColumns}
		/>
	{:else if activeSubTab === 'hidden'}
		<IntelCategoryView
			title="Hidden Networks"
			description={INTEL_DESCRIPTIONS.hidden}
			targets={$hiddenNetworks}
			reconStatus={$reconStatus}
			onRefresh={triggerRecon}
		/>
	{:else if activeSubTab === 'busy-aps'}
		<IntelCategoryView
			title="Busy Access Points"
			description={INTEL_DESCRIPTIONS['busy-aps']}
			targets={$busyAPs}
			reconStatus={$reconStatus}
			onRefresh={triggerRecon}
			extraColumns={busyExtraColumns}
		/>
	{:else if activeSubTab === 'gps'}
		<IntelCategoryView
			title="GPS Tracked"
			description={INTEL_DESCRIPTIONS.gps}
			targets={$gpsTracked}
			reconStatus={$reconStatus}
			onRefresh={triggerRecon}
			extraColumns={gpsExtraColumns}
		/>
	{:else if activeSubTab === 'alerts'}
		<IntelCategoryView
			title="Security Alerts"
			description={INTEL_DESCRIPTIONS.alerts}
			targets={$reconTargets}
			alerts={$reconAlerts}
			reconStatus={$reconStatus}
			onRefresh={triggerRecon}
		/>
	{:else}
		<DeviceTable
			devices={renderedDevices}
			{selectedMAC}
			{expandedMAC}
			{sortColumn}
			{sortDirection}
			onSort={handleSort}
			onRowClick={handleRowClick}
		/>
	{/if}
</div>

<style>
	.devices-panel {
		display: flex;
		flex-direction: column;
		height: 100%;
		background: var(--card);
	}

	.whitelist-view {
		flex: 1;
		overflow: auto;
	}
</style>
